spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    #password: root
    url: jdbc:mysql://localhost:3306/car_manage?serverTimezone=UTC&characterEncoding=utf-8
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
server:
  port: 8089

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql