
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/car_manage?serverTimezone=UTC&characterEncoding=utf-8
  thymeleaf:
    cache: false
server:
  port: 8088